<a href="https://colab.research.google.com/github/aryanjuyal/insurance_regression_model/blob/main/regression_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Imported the Modules

In [32]:
!git clone https://github.com/aryanjuyal/insurance_regression_model.git

fatal: destination path 'insurance_regression_model' already exists and is not an empty directory.


In [2]:
import pandas as pd
import numpy as np

Made Dataframe from the dataset

In [3]:
dataset = pd.read_csv('insurance.csv')

Convert gender and Smoker in Binary

In [17]:
dataset['sex'] = dataset['sex'].replace({"male":"1","female":"0"})
dataset['smoker'] = dataset['smoker'].replace({"yes":"1","no":"0"})


Separate Dependent and Independent variables

In [5]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Encoded categorial variable that is region using OneHotEncoder

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 0.0 ... 27.9 0 1]
 [0.0 0.0 1.0 ... 33.77 1 0]
 [0.0 0.0 1.0 ... 33.0 3 0]
 ...
 [0.0 0.0 1.0 ... 36.85 0 0]
 [0.0 0.0 0.0 ... 25.8 0 0]
 [0.0 1.0 0.0 ... 29.07 0 1]]


Split the data for Training and Testing

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

Training the model

In [18]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

Get the output of testing set

In [19]:
y_pred = regressor.predict(X_test)

Compared the result of original charges to predicted charges by our model

In [26]:

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[1.11699271e+04 9.72453000e+03]
 [9.48670909e+03 8.54769130e+03]
 [3.81811231e+04 4.57020223e+04]
 [1.62663133e+04 1.29500712e+04]
 [6.91464801e+03 9.64425250e+03]
 [3.96348488e+03 4.50033925e+03]
 [1.57939691e+03 2.19818985e+03]
 [1.43852566e+04 1.14367381e+04]
 [9.01257970e+03 7.53716390e+03]
 [7.50846068e+03 5.42502335e+03]
 [4.49176728e+03 6.75303800e+03]
 [1.02795839e+04 1.04939458e+04]
 [8.80129751e+03 7.33774800e+03]
 [3.79802013e+03 4.18509790e+03]
 [2.79262010e+04 1.83107420e+04]
 [1.07151158e+04 1.07026424e+04]
 [1.12889756e+04 1.25236048e+04]
 [6.10501768e+03 3.49054910e+03]
 [8.24104117e+03 6.45784340e+03]
 [2.71445089e+04 3.34758172e+04]
 [3.36440910e+04 2.39673831e+04]
 [1.43551043e+04 1.26433778e+04]
 [1.17372043e+04 2.30455662e+04]
 [3.21374335e+04 2.30654207e+04]
 [4.17005913e+03 1.67463230e+03]
 [9.25496051e+03 4.66760765e+03]
 [1.08433751e+03 3.73262510e+03]
 [9.80417085e+03 7.68267000e+03]
 [3.77104596e+03 3.75662160e+03]
 [1.04318587e+04 8.41346305e+03]
 [9.009317

this is how a value is predicted using model when input is given

In [22]:
print(regressor.predict([[1,0,0,0,18,1,33,2,1]]))

[28288.68210697]
